[package]
name = "display-nvidia-mem"
version = "0.1.0"
authors = ["Árni Dagur <arni@dagur.eu>"]
edition = "2021"

[dependencies]
nvml-wrapper = "0.8.0"
quick-error = "2.0"
number_prefix = "0.4.0"

[profile.release]
lto = true
codegen-units = 1
